### ISSUE TITLE
TT WebBased (Comment endpoint) _Signature= key

### ISSUE THREAD

**Issue by h4ck1th4rd** [AndrewAndrea/spider_demo#2]
Hi,

How are you? I am sorry of posting this off rep-topic. but I just wonder are you able to know how the comment endpoint generate a unique signature key? for each comment?

I got this: 

https://gist.github.com/mzaboss/582ba2410a9d1846aba6e025d2c2dfc3

Thank you,
regards.

**Comment by AndrewAndrea** [comment]
Sorry, I don’t quite understand what you mean, do you need the signature of the web site or the signature of TikTok APP

**Comment by AndrewAndrea** [comment]
Copy all js directly, run it with node, make up what is missing

**Comment by h4ck1th4rd** [comment]
> Copy all js directly, run it with node, make up what is missing

Thank you for your response am very happy for that. Actually am not a JS developer. I don't know anything about it. I wonder if i can hire you? to do the job or if you can help me with.

I just want to know how & and be able to generate the signature key for TT web based comment endpoint as simple as that.

Thank you in advance.

PS: Got Skype or telegram for instant chat?

**Comment by AndrewAndrea** [comment]
Telegram sent you a message. I will close this

**Comment by h4ck1th4rd** [comment]
You never replied me back in telegram? not interested anymore?

**Comment by h4ck1th4rd** [comment]
any good or you feedup?
